# SPDX-FileCopyrightText: Copyright (c) 2026 Den Rozhnovskiy <rozhnovskiydenis@gmail.com>
# SPDX-License-Identifier: MIT
"""Optional command lockfile for ckdn.toml governance (CI / review)."""

from __future__ import annotations

import hashlib
import tomllib
from pathlib import Path

from ckdn.config import Config

LOCK_NAME = "ckdn.lock.toml"
_POLICY_PROBE = "_ckdn_policy_probe"


def command_digest(command: str) -> str:
    return hashlib.sha256(command.encode("utf-8")).hexdigest()


def default_lock_path(cfg: Config) -> Path:
    return cfg.config_path.parent / LOCK_NAME


def write_config_lock(cfg: Config, path: Path | None = None) -> Path:
    """Write ``ckdn.lock.toml`` with a SHA-256 of each atomic check command."""
    target = path or default_lock_path(cfg)
    lines = [
        "# Generated by `ckdn lock-config`. Commit to enforce command review in CI.\n",
        f"# Source: {cfg.config_path.name}\n\n",
    ]
    for name in sorted(cfg.checks):
        check = cfg.checks[name]
        if check.is_alias or check.command is None:
            continue
        digest = command_digest(check.command)
        lines.append(f'[check.{name}]\ncommand_sha256 = "{digest}"\n\n')
    target.write_text("".join(lines), encoding="utf-8")
    return target


def verify_config_lock(
    cfg: Config,
    path: Path | None = None,
) -> list[str]:
    """Compare atomic check commands against a lock file. Returns error strings."""
    lock_path = path or default_lock_path(cfg)
    if not lock_path.exists():
        return [f"lock file not found: {lock_path} (run `ckdn lock-config`)"]
    try:
        data = tomllib.loads(lock_path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError as exc:
        return [f"invalid TOML in {lock_path}: {exc}"]

    locked = data.get("check", {})
    if not isinstance(locked, dict):
        return [f"{lock_path}: missing [check.<name>] tables"]

    errors: list[str] = []
    for name, check in sorted(cfg.checks.items()):
        if check.is_alias or check.command is None:
            continue
        entry = locked.get(name)
        if not isinstance(entry, dict):
            errors.append(f"[check.{name}] missing from {lock_path.name}")
            continue
        expected = entry.get("command_sha256")
        if not isinstance(expected, str) or not expected:
            errors.append(f"[check.{name}] missing command_sha256 in lock file")
            continue
        actual = command_digest(check.command)
        if actual != expected:
            errors.append(
                f"[check.{name}] command changed since lock "
                f"(expected {expected[:12]}…, got {actual[:12]}…)"
            )

    errors.extend(
        f"[check.{name}] present in lock file but not in config"
        for name in sorted(locked)
        if name not in cfg.checks
    )
    return errors


def verify_config(
    cfg: Config,
    *,
    locked: bool = False,
    lock_path: Path | None = None,
) -> list[str]:
    """Validate command policy and optionally the lock file. Returns error strings."""
    from ckdn.command_policy import CommandPolicyError, validate_command
    from ckdn.runner import build_tokens

    errors: list[str] = []
    probe_dir = cfg.cwd / _POLICY_PROBE

    for name in sorted(cfg.checks):
        check = cfg.checks[name]
        if check.is_alias or check.command is None:
            continue
        try:
            tokens = build_tokens(check.command, probe_dir, [])
            validate_command(
                check.command,
                [],
                cwd=cfg.cwd,
                policy=cfg.run.command_policy,
                allowlist_prefixes=cfg.run.command_allowlist,
                tokens=tokens,
            )
        except CommandPolicyError as exc:
            errors.append(f"[check.{name}] {exc}")

    if locked:
        errors.extend(verify_config_lock(cfg, lock_path))
    return errors
